fos_rest:
  param_fetcher_listener: true
  format_listener:
    enabled: true
    rules:
      - { path: '^/api', priorities: ['json', 'xml'], fallback_format: json, prefer_extension: false }
      - { path: '^/', priorities: ['json'], fallback_format: json, prefer_extension: false }
  view:
    view_response_listener: true